package Catch;

public class Trycatch {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
			int a[]=new int[3];
			try{
				a[3]=8;
				}
			catch(Exception ae){
				System.out.println("ArrayINdexOutOfBounds Exception");
				System.out.println(ae.getMessage());
				}
			finally{
				System.out.println("The array size is"+a.length);
				}
		}

}
